let words = [
  { en: 'elevator', rus: 'лифт' },
  { en: 'turn', rus: 'поворачивать' },
  { en: 'gate', rus: 'выход на посадку' },
  { en: 'boarding', rus: 'посадка на рейс' },
  { en: 'customs', rus: 'таможня' },
  { en: 'carry-on bag', rus: 'ручная кладь' },
  { en: 'baggage', rus: 'багаж' },
  { en: 'boarding pass', rus: 'посадочный талон' },
  { en: 'delayed', rus: 'задержанный (рейс)' },
  { en: 'check-in', rus: 'регистрация' },
  { en: 'produce', rus: 'производить' },
  { en: 'carry', rus: 'нести' },
  { en: 'supply', rus: 'снабжать, восполнять' },
  { en: 'provide', rus: 'предоставлять, подготавливать' },
  { en: 'decide', rus: 'решать' },
  { en: 'consider', rus: 'обдумывать, принимать во внимание' },
  { en: 'get lost', rus: 'заблудиться' },
  { en: 'treat', rus: 'угощать' },
  { en: 'toast', rus: 'тост' },
  { en: 'anniversary', rus: 'годовщина' },
  { en: 'special occasion', rus: 'особый повод' },
  { en: 'hitchhike', rus: 'путешествовать автостопом' },
  { en: 'cruise', rus: 'круиз' },
  { en: 'train station', rus: 'вокзал' },
  { en: 'destination', rus: 'пункт назначения' },
  { en: 'suitcase', rus: 'чемодан' },
  { en: 'dressy', rus: 'нарядный' },
  { en: 'baggy', rus: 'свободный, болтающийся' },
  { en: 'tight', rus: 'тесный' },
  { en: 'dowdy', rus: 'старомодный' },
  { en: 'trendy', rus: 'модный' },
  { en: 'stylish', rus: 'стильный' },
  { en: 'ballet flats', rus: 'балетки' },
  { en: 'sneakers', rus: 'кроссовки' },
  { en: 'wedges', rus: 'туфли на платформе' },
  { en: 'sandals', rus: 'босоножки' },
  { en: 'ankle boots', rus: 'ботильоны' },
  { en: 'shoestrings', rus: 'шнурки' },
  { en: 'heel', rus: 'каблук' },
  { en: 'pumps', rus: 'туфли на каблуках' },
  { en: 'shelf', rus: 'полка' },
  { en: 'nail', rus: 'гвоздь' },
  { en: 'wallpaper', rus: 'обои' },
  { en: 'hang', rus: 'вешать' },
  { en: 'drill', rus: 'сверлить' },
  { en: 'furnish', rus: 'обставлять' },
  { en: 'fix', rus: 'чинить' },
  { en: 'raplace', rus: 'заменять' },
  { en: 'repaint', rus: 'перекрашивать' },
  { en: 'renovation', rus: 'ремонт' },
  { en: 'lift', rus: 'поднимать' },
  { en: 'lie', rus: 'лежать' },
  { en: 'vacation', rus: 'отпуск' },
  { en: 'octopus', rus: 'осьминог' },
  { en: 'text', rus: 'посылать СМС' },
  { en: 'cocktail', rus: 'коктейль' },
  { en: 'milkshake', rus: 'молочный коктейль' },
  { en: 'sparkling water', rus: 'газированная вода' },
  { en: 'barely', rus: 'едва' },
  { en: 'almost', rus: 'почти' },
  { en: 'pretty', rus: 'довольно-таки' },
  { en: 'quite', rus: 'довольно-таки, весьма' },
  { en: 'completely', rus: 'полностью' },
  { en: 'extremely', rus: 'крайне' },
  { en: 'caring', rus: 'заботливый' },
  { en: 'polite', rus: 'вежливый' },
  { en: 'kind', rus: 'добрый' },
  { en: 'honest', rus: 'честный' },
  { en: 'humble', rus: 'скромный' },
  { en: 'courageous', rus: 'храбрый' },
  { en: 'wise', rus: 'мудрый' },
  { en: 'remote', rus: 'пульт' },
  { en: 'scrambled eggs', rus: 'яичница-болтунья' },
  { en: 'soft-boiled egg', rus: 'яйцо всмятку' },
  { en: 'oatmeal', rus: 'овсяная каша' },
  { en: 'cereal', rus: 'хлопья, сухой завтрак' },
  { en: 'tablet', rus: 'планшет' },
  { en: 'textbook', rus: 'учебник' },
  { en: 'notebook', rus: 'тетрадь' },
  { en: 'ruler', rus: 'линейка' },
  { en: 'pencil case', rus: 'пенал' },
  { en: 'eraser', rus: 'ластик' },
  { en: 'pencil', rus: 'карандаш' },
  { en: 'upstairs', rus: 'вверх по лестнице' },
  { en: 'downstairs', rus: 'вниз по лестнице' },
  { en: 'backwards', rus: 'задом наперёд' },
  { en: 'forward', rus: 'вперёд' },
  { en: 'sick', rus: 'больной' },
  { en: 'groceries', rus: 'продукты' },
  { en: 'far', rus: 'далеко' },
]

function randomInteger(min, max) {
  // случайное число от min до (max+1)
  let rand = min + Math.random() * (max + 1 - min);
  return Math.floor(rand);
}

for (let i=0; i <= 20; i++) {

  let wordNumber = randomInteger(0, words.length-1)
  console.log(wordNumber);
  let doKnow = confirm( words[wordNumber].rus);

  if (doKnow == false) {
      alert( words[wordNumber].en )
  }
}
